sudo: required

language: python

services:
  - docker

before_install:
- echo $LICENSE | base64 --decode > /tmp/stardog-license-key.bin
- ls -l /tmp/stardog-license-key.bin
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD complexible-eps-docker.jfrog.io
- docker run -v /tmp/stardog-license-key.bin:/var/opt/stardog/stardog-license-key.bin -p 127.0.0.1:5820:5820 -d -it complexible-eps-docker.jfrog.io/stardog:5.0

script:
- yarn test
